name: Cargo crate CI/CD

on:
  workflow_call:
    inputs:
      crate-name:
        required: true
        type: string

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "called for ${{ inputs.crate-name }}"
